# Website info
title: Jaydeep Malik
acronym: jd
tagline: Everything that Makes Sense ğŸ˜
email: hi@jaydeepmalik.com
description: Jaydeep Malik AKA JD's portfolio, blog and resources. He is passionate about cyber security and fitness. ğŸ‘½ ğŸ‘¾ ğŸ¤–

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaydeepmalik.com" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 6
paginate_path: /blog/:num/
# Social users - twitter, instagram, github, gitlab, codepen profile, youtube and facebook
social:
  twitter: jaydeepmalik
  github: jaydeepmalik
  youtube_channel: channel
  facebook: jaydeepmalik
  instagram: jaydeepmalik

# Compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]

favicon: favicon.ico # favicon name in assets/img/

permalink: /:year/:month/:title/

# Assets - We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed
# Build settings
env: development
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - .git*
  - .gitignore
  - vendor
